### PR TITLE
sssstool - inspired by ssss

### PR DESCRIPTION
**Pull request by z-eos**
script to distribute/reconstruct secret/s, inspired by [ssss](http://point-at-infinity.org/ssss/)

### CODE REVIEW

**Comment by z-eos** [comment]
error

**Comment by z-eos** [comment]
script to distribute/reconstruct secret/s, inspired by [ssss](http://point-at-infinity.org/ssss/)

**Comment by und3f** [comment]
Hello, this is a great tool, thank you.
I found that you are using some huge dependencies that are not required for the original Crypt::SSSS module
Would you like to release sssstool as a separate tool, e.g. App::SSSSTool?

**Comment by z-eos** [comment]
hi
the hugest dependency is Data::Printer... it's easy to use Data::Dumper instead
most of the rest is in perl distribution

are such changes acceptable for the script to be included in the module?

To be honest, I believe it's much better to have such a tool as part of the module (like it is with exiftool, acmeman, xkpasswd)

**Comment by und3f** [comment]
>> the hugest dependency is Data::Printer... it's easy to use Data::Dumper instead
most of the rest is in perl distribution

>> are such changes acceptable for the script to be included in the module?

Yes, it is acceptable, please minimize required dependencies to core modules. 
Such tool is a great improvement for the module!

**Comment by z-eos** [comment]
just've pushed changes (a bit more than initial idea though)

**Comment by und3f** [comment]
Could we leave alone Crypt::Primes or make it optional? It is heavy.

**Comment by und3f** [comment]
Thank you, I'll review it soon

**Comment by und3f** [comment]
Is it necessary to change SSSS.pm and SSSS/Message.pm ? At a moment I see that your changes broke the actual code and test fails

````
t/message.t .. ok
t/ssss.t ..... 1/17
#   Failed test 'p = 65537 secret reconstructed'                               
#   at t/ssss.t line 100.
#          got: ''
#     expected: '       '
# Looks like you failed 1 test of 17.

**Comment by z-eos** [comment]
no necessity, just've offered tiny amendment (from mý point of view)

**Comment by und3f** [comment]
Zeus, I am sorry but your changes to SSSS.pm are unacceptable as they brake the tests and make module unworkable.
Please do not use Perl 5.20 features as module is marked to work with the Perl 5.08

Also please provide tests for sssstool

Please check updated version of Crypt:SSSS with the travis enabled

**Comment by z-eos** [comment]
- previous changes to SSSS.pm were reverted
- fix to remove padding `\0` characters from chunks to correctly build the result
- test for sssstool added
- all tests are successfully passed except for perl 5.8, 5.10 and 5.12 for which travis output contains error 404 and `perl-5.8.tar.bz2: Cannot open: No such file or directory`

**Comment by z-eos** [comment]
is it possible to do anything with those broken auto checks?

**Comment by und3f** [comment]
You have to fix commit code to satisfy checks at t/

**Pull request closed without merging**
